name: feedr-backend
version: 0.0.0
author: Niklas Rosenstein <rosensteinniklas@gmail.com>
description: Package description here.
requirements:
- python ^3.5
- databind.core ^0.5.0
- databind.yaml ^0.1.1
- requests ^2.24.0
- Flask ^1.1.2
- SQLAlchemy ^1.3.19
- nr.proxy ^1.0.1
typed: true
